// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/prtcltrans.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcTransCore.Services {

  /// <summary>Holder for reflection information generated from protos/prtcltrans.proto</summary>
  public static partial class PrtcltransReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/prtcltrans.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PrtcltransReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdwcm90b3MvcHJ0Y2x0cmFucy5wcm90bxIWR3JwY1RyYW5zQ29yZS5TZXJ2",
            "aWNlcxoXcHJvdG9zL3NvdXJjZS9hbnkucHJvdG8aGXByb3Rvcy9zb3VyY2Uv",
            "ZW1wdHkucHJvdG8iYwoIVHJhbnNSZXESCwoDc2lkGAEgASgDEgsKA29wdBgC",
            "IAEoBRIMCgRkYXRhGAMgASgJEgsKA2NpZBgEIAEoCRIiCgRleHRzGAUgASgL",
            "MhQuZ29vZ2xlLnByb3RvYnVmLkFueSJkCghUcmFuc1JlcxILCgNzaWQYASAB",
            "KAMSCwoDb3B0GAIgASgFEgwKBGRhdGEYAyABKAkSDAoEY29kZRgEIAEoBRIi",
            "CgRleHRzGAUgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueTK7BAoUR3JwY1Ry",
            "YW5zQ29yZVNlcnZpY2USVQoPR3JwY0dlbmVyYWxDYWxsEiAuR3JwY1RyYW5z",
            "Q29yZS5TZXJ2aWNlcy5UcmFuc1JlcRogLkdycGNUcmFuc0NvcmUuU2Vydmlj",
            "ZXMuVHJhbnNSZXMSWgoeR3JwY0dlbmVyYWxDYWxsV2l0aG91dFJlc3BvbnNl",
            "EiAuR3JwY1RyYW5zQ29yZS5TZXJ2aWNlcy5UcmFuc1JlcRoWLmdvb2dsZS5w",
            "cm90b2J1Zi5FbXB0eRJaCh5HcnBjR2VuZXJhbENhbGxXaXRob3V0UmVxcGFy",
            "YW0SFi5nb29nbGUucHJvdG9idWYuRW1wdHkaIC5HcnBjVHJhbnNDb3JlLlNl",
            "cnZpY2VzLlRyYW5zUmVzElsKE0dycGNDbGllbnRXYXlTdHJlYW0SIC5HcnBj",
            "VHJhbnNDb3JlLlNlcnZpY2VzLlRyYW5zUmVxGiAuR3JwY1RyYW5zQ29yZS5T",
            "ZXJ2aWNlcy5UcmFuc1JlcygBElsKE0dycGNTZXJ2ZXJXYXlTdHJlYW0SIC5H",
            "cnBjVHJhbnNDb3JlLlNlcnZpY2VzLlRyYW5zUmVxGiAuR3JwY1RyYW5zQ29y",
            "ZS5TZXJ2aWNlcy5UcmFuc1JlczABEloKEEdycGNUd29XYXlTdHJlYW0SIC5H",
            "cnBjVHJhbnNDb3JlLlNlcnZpY2VzLlRyYW5zUmVxGiAuR3JwY1RyYW5zQ29y",
            "ZS5TZXJ2aWNlcy5UcmFuc1JlcygBMAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcTransCore.Services.TransReq), global::GrpcTransCore.Services.TransReq.Parser, new[]{ "Sid", "Opt", "Data", "Cid", "Exts" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcTransCore.Services.TransRes), global::GrpcTransCore.Services.TransRes.Parser, new[]{ "Sid", "Opt", "Data", "Code", "Exts" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TransReq : pb::IMessage<TransReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransReq> _parser = new pb::MessageParser<TransReq>(() => new TransReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcTransCore.Services.PrtcltransReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransReq(TransReq other) : this() {
      sid_ = other.sid_;
      opt_ = other.opt_;
      data_ = other.data_;
      cid_ = other.cid_;
      exts_ = other.exts_ != null ? other.exts_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransReq Clone() {
      return new TransReq(this);
    }

    /// <summary>Field number for the "sid" field.</summary>
    public const int SidFieldNumber = 1;
    private long sid_;
    /// <summary>
    /// 单次请求的唯一标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sid {
      get { return sid_; }
      set {
        sid_ = value;
      }
    }

    /// <summary>Field number for the "opt" field.</summary>
    public const int OptFieldNumber = 2;
    private int opt_;
    /// <summary>
    /// 操作类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Opt {
      get { return opt_; }
      set {
        opt_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private string data_ = "";
    /// <summary>
    /// 数据 json
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cid" field.</summary>
    public const int CidFieldNumber = 4;
    private string cid_ = "";
    /// <summary>
    /// 客户端id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cid {
      get { return cid_; }
      set {
        cid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "exts" field.</summary>
    public const int ExtsFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Any exts_;
    /// <summary>
    /// 扩展
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Exts {
      get { return exts_; }
      set {
        exts_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sid != other.Sid) return false;
      if (Opt != other.Opt) return false;
      if (Data != other.Data) return false;
      if (Cid != other.Cid) return false;
      if (!object.Equals(Exts, other.Exts)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Sid != 0L) hash ^= Sid.GetHashCode();
      if (Opt != 0) hash ^= Opt.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Cid.Length != 0) hash ^= Cid.GetHashCode();
      if (exts_ != null) hash ^= Exts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Cid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Cid);
      }
      if (exts_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Exts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Cid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Cid);
      }
      if (exts_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Exts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Sid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Sid);
      }
      if (Opt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Opt);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (Cid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cid);
      }
      if (exts_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Exts);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransReq other) {
      if (other == null) {
        return;
      }
      if (other.Sid != 0L) {
        Sid = other.Sid;
      }
      if (other.Opt != 0) {
        Opt = other.Opt;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Cid.Length != 0) {
        Cid = other.Cid;
      }
      if (other.exts_ != null) {
        if (exts_ == null) {
          Exts = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Exts.MergeFrom(other.Exts);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Cid = input.ReadString();
            break;
          }
          case 42: {
            if (exts_ == null) {
              Exts = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Exts);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Cid = input.ReadString();
            break;
          }
          case 42: {
            if (exts_ == null) {
              Exts = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Exts);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TransRes : pb::IMessage<TransRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransRes> _parser = new pb::MessageParser<TransRes>(() => new TransRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcTransCore.Services.PrtcltransReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransRes(TransRes other) : this() {
      sid_ = other.sid_;
      opt_ = other.opt_;
      data_ = other.data_;
      code_ = other.code_;
      exts_ = other.exts_ != null ? other.exts_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransRes Clone() {
      return new TransRes(this);
    }

    /// <summary>Field number for the "sid" field.</summary>
    public const int SidFieldNumber = 1;
    private long sid_;
    /// <summary>
    /// 某次请求的唯一标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sid {
      get { return sid_; }
      set {
        sid_ = value;
      }
    }

    /// <summary>Field number for the "opt" field.</summary>
    public const int OptFieldNumber = 2;
    private int opt_;
    /// <summary>
    /// 操作类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Opt {
      get { return opt_; }
      set {
        opt_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private string data_ = "";
    /// <summary>
    /// 数据 json
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 4;
    private int code_;
    /// <summary>
    /// 状态码 200:成功  其他失败 500:服务器错误
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "exts" field.</summary>
    public const int ExtsFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Any exts_;
    /// <summary>
    /// 扩展参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Exts {
      get { return exts_; }
      set {
        exts_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sid != other.Sid) return false;
      if (Opt != other.Opt) return false;
      if (Data != other.Data) return false;
      if (Code != other.Code) return false;
      if (!object.Equals(Exts, other.Exts)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Sid != 0L) hash ^= Sid.GetHashCode();
      if (Opt != 0) hash ^= Opt.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Code != 0) hash ^= Code.GetHashCode();
      if (exts_ != null) hash ^= Exts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Code != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Code);
      }
      if (exts_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Exts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Code != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Code);
      }
      if (exts_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Exts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Sid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Sid);
      }
      if (Opt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Opt);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (exts_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Exts);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransRes other) {
      if (other == null) {
        return;
      }
      if (other.Sid != 0L) {
        Sid = other.Sid;
      }
      if (other.Opt != 0) {
        Opt = other.Opt;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.exts_ != null) {
        if (exts_ == null) {
          Exts = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Exts.MergeFrom(other.Exts);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 32: {
            Code = input.ReadInt32();
            break;
          }
          case 42: {
            if (exts_ == null) {
              Exts = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Exts);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 32: {
            Code = input.ReadInt32();
            break;
          }
          case 42: {
            if (exts_ == null) {
              Exts = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Exts);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
