<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet.AspNetCore" Version="5.1.0.1559" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common.CoreLib\Common.CoreLib.csproj" />
  </ItemGroup>

</Project>
